
#include "hardware_init.h"
#include "application_init.h"


#define EPWM_PERIOD         USER_PWM_PERIOD
#define EPWM_DEAD_TIME      (USER_PWM_DEADTIME_US*USER_PWM_CLK_MHZ)
#define EPWM_HALF_PERIOD    (EPWM_PERIOD>>1)


void cfg_EPWM_GPIO(void);
void cfg_EPWM11(void);
void cfg_EPWM12(void);
void cfg_EPWM13(void);
void cfg_EPWM16(void);




void cfg_PWM(void)
{
    EPWM_Reset(EPWM11_SFR);
    EPWM_Reset(EPWM12_SFR);
    EPWM_Reset(EPWM13_SFR);
    EPWM_Reset(EPWM16_SFR);
	cfg_EPWM_GPIO();
	cfg_EPWM11();
	cfg_EPWM12();
	cfg_EPWM13();
	//cfg_EPWM16();
	pwm_disable();
}

void cfg_EPWM_GPIO(void)
{
	GPIO_Write_Mode_Bits(GPIOF_SFR,GPIO_PIN_MASK_3,GPIO_MODE_RMP);  //PWM11A-PF3
	GPIO_Write_Mode_Bits(GPIOF_SFR,GPIO_PIN_MASK_1,GPIO_MODE_RMP);  //PWM11B-PF1
	GPIO_Write_Mode_Bits(GPIOF_SFR,GPIO_PIN_MASK_2,GPIO_MODE_RMP);  //PWM12A-PF2
	GPIO_Write_Mode_Bits(GPIOF_SFR,GPIO_PIN_MASK_0,GPIO_MODE_RMP);  //PWM12B-PF0
	GPIO_Write_Mode_Bits(GPIOF_SFR,GPIO_PIN_MASK_5,GPIO_MODE_RMP);  //PWM13A-PF5
	GPIO_Write_Mode_Bits(GPIOB_SFR,GPIO_PIN_MASK_6,GPIO_MODE_RMP);  //PWM13B-PB6
	GPIO_Write_Mode_Bits(GPIOF_SFR,GPIO_PIN_MASK_7,GPIO_MODE_RMP);  //PWM16A-PF7

	GPIO_Pin_RMP_Config(GPIOF_SFR,GPIO_Pin_Num_3,GPIO_RMP_PAGE3_AF1);  //EPWM11A-PF3
	GPIO_Pin_RMP_Config(GPIOF_SFR,GPIO_Pin_Num_1,GPIO_RMP_PAGE3_AF1);  //EPWM11B-PF1
	GPIO_Pin_RMP_Config(GPIOF_SFR,GPIO_Pin_Num_2,GPIO_RMP_PAGE3_AF1);  //EPWM12A-PF2
	GPIO_Pin_RMP_Config(GPIOF_SFR,GPIO_Pin_Num_0,GPIO_RMP_PAGE3_AF1);  //EPWM12B-PF0
	GPIO_Pin_RMP_Config(GPIOF_SFR,GPIO_Pin_Num_5,GPIO_RMP_PAGE3_AF1);  //EPWM13A-PF5
	GPIO_Pin_RMP_Config(GPIOB_SFR,GPIO_Pin_Num_6,GPIO_RMP_PAGE3_AF5);  //EPWM13B-PB6
	GPIO_Pin_RMP_Config(GPIOF_SFR,GPIO_Pin_Num_7,GPIO_RMP_PAGE3_AF1);  //EPWM16A-PF7
}

void cfg_EPWM11(void)
{
	EPWM_Work_Mode_Config(EPWM11_SFR,EPWM_TIMER_MODE);
	EPWM_Work_Clock_Select(EPWM11_SFR,EPWM_CLK_SCLK);  //EPWM_CLK=SCLK
	EPWM_TxPRSC_Value_Config(EPWM11_SFR,0);  //1:1
	EPWM_TxPHS_Value_Config(EPWM11_SFR,0);

	EPWM_Counter_Mode_Select(EPWM11_SFR,EPWM_COUNT_UP_DOWM_OF);  //UP DOWN MODE

	EPWM_Phase_Register_Loading_Enable(EPWM11_SFR,TRUE);
	EPWM_Phase_Direction_Config(EPWM11_SFR,EPWM_SYNC_TRIGGER_UP);
	EPWM_SYNC_Event_Out_Select(EPWM11_SFR,EPWM_SYNC_EVENT_OUT_COUNT0);  //CNT=0

	EPWM11_SFR->PPX = EPWM_PERIOD;
	EPWM11_SFR->RA = EPWM_HALF_PERIOD;
	EPWM11_SFR->RB = EPWM_HALF_PERIOD;

	EPWM_EPWMxAB_OUTPUT_Select(EPWM11_SFR,EPWM_REGISTER_A,EPWM_CERA_DU_EPWMAB_OUT,EPWM_OUT_HIGH);    //RA-UP HIGH
	EPWM_EPWMxAB_OUTPUT_Select(EPWM11_SFR,EPWM_REGISTER_A,EPWM_CERA_DD_EPWMAB_OUT,EPWM_OUT_LOW);   //RA-DOWN LOW
	EPWM_Continuous_Mandatory_Output_Config(EPWM11_SFR,EPWM_REGISTER_A,EPWM_OUT_PROHIBIT);

	//DB
	EPWM_Dead_Zone_Input_Select(EPWM11_SFR,EPWM_EPWMA_UP_EPWMA_DOWM);
	EPWM_Dead_Zone_Output_Polarity_Select(EPWM11_SFR,EPWM_EPWMA_NTOGGLE_EPWMB_TOGGLE);
	EPWM_Dead_Zone_Output_Select(EPWM11_SFR,EPWM_UP_ENABLE_DOWN_ENABLE);
	EPWM_Dead_Zone_Time_Config(EPWM11_SFR,EPWM_UP_EDGE_DEAD_ZONE,EPWM_DEAD_TIME);
	EPWM_Dead_Zone_Time_Config(EPWM11_SFR,EPWM_DOWM_EDGE_DEAD_ZONE,EPWM_DEAD_TIME);

	//TZ
	EPWM_Auto_ShowDown_Source_Select(EPWM11_SFR,EPWM_AUTO_SHOWDOWN_SOURCE_TZ4_HIGH);  //TZ4

    //trigger AD
	EPWM_Trigger_AD_Event_Mode_Select(EPWM11_SFR,EPWM_TRIGGER_AD_EVENT0,EPWM_TRIGGER_AD_UP);
	EPWM_Trigger_AD_Event_Mode_Select(EPWM11_SFR,EPWM_TRIGGER_AD_EVENT1,EPWM_TRIGGER_AD_UP);
	EPWM_Trigger_Event_Cycle_Select(EPWM11_SFR,EPWM_TRIGGER_AD_EVENT0,EPWM_1_TRIGGER_EVENT_TRIGGER_AD);
	EPWM_Trigger_Event_Cycle_Select(EPWM11_SFR,EPWM_TRIGGER_AD_EVENT1,EPWM_1_TRIGGER_EVENT_TRIGGER_AD);
	EPWM_Trigger_AD_Event_Select(EPWM11_SFR,EPWM_TRIGGER_AD_EVENT0,EPWM_TIMER_EQUAL_0PULSE);
	EPWM_Trigger_AD_Event_Select(EPWM11_SFR,EPWM_TRIGGER_AD_EVENT1,EPWM_TIMER_EQUAL_PPPULSE);
	EPWM_Trigger_AD_Event_Enable(EPWM11_SFR,EPWM_TRIGGER_AD_EVENT0,TRUE);
	EPWM_Trigger_AD_Event_Enable(EPWM11_SFR,EPWM_TRIGGER_AD_EVENT1,TRUE);

	//interrupt
	//EPWM_INT_Enable(EPWM11_SFR,EPWM_COUNT_EQUAL_EPWMRA,FALSE);

	//update
	EPWM_Global_Loading_Enable(EPWM11_SFR,FALSE);
	EPWM_Updata_Event_Enable(EPWM11_SFR,TRUE);
	EPWM_Updata_Event_Generate_Enable(EPWM11_SFR,TRUE);


	EPWM_Enable(EPWM11_SFR,FALSE);
}

void cfg_EPWM12(void)
{
	EPWM_Work_Mode_Config(EPWM12_SFR,EPWM_TIMER_MODE);
	EPWM_Work_Clock_Select(EPWM12_SFR,EPWM_CLK_SCLK);  //EPWM_CLK=SCLK
	EPWM_TxPRSC_Value_Config(EPWM12_SFR,0);  //1:1
	EPWM_TxPHS_Value_Config(EPWM12_SFR,2);

	EPWM_Counter_Mode_Select(EPWM12_SFR,EPWM_COUNT_UP_DOWM_OF);  //UP DOWN MODE

	EPWM_Phase_Register_Loading_Enable(EPWM12_SFR,TRUE);
	EPWM_Phase_Direction_Config(EPWM12_SFR,EPWM_SYNC_TRIGGER_UP);
	EPWM_SYNC_Event_Out_Select(EPWM12_SFR,EPWM_SYNC_EVENT_OUT_EPWM_SWF);  //SYNCI/SWFSYNC

	EPWM12_SFR->PPX = EPWM_PERIOD;
	EPWM12_SFR->RA = EPWM_HALF_PERIOD;
	EPWM12_SFR->RB = EPWM_HALF_PERIOD;

	EPWM_EPWMxAB_OUTPUT_Select(EPWM12_SFR,EPWM_REGISTER_A,EPWM_CERA_DU_EPWMAB_OUT,EPWM_OUT_HIGH);    //RA-UP HIGH
	EPWM_EPWMxAB_OUTPUT_Select(EPWM12_SFR,EPWM_REGISTER_A,EPWM_CERA_DD_EPWMAB_OUT,EPWM_OUT_LOW);   //RA-DOWN LOW
	EPWM_Continuous_Mandatory_Output_Config(EPWM12_SFR,EPWM_REGISTER_A,EPWM_OUT_PROHIBIT);

	//DB
	EPWM_Dead_Zone_Input_Select(EPWM12_SFR,EPWM_EPWMA_UP_EPWMA_DOWM);
	EPWM_Dead_Zone_Output_Polarity_Select(EPWM12_SFR,EPWM_EPWMA_NTOGGLE_EPWMB_TOGGLE);
	EPWM_Dead_Zone_Output_Select(EPWM12_SFR,EPWM_UP_ENABLE_DOWN_ENABLE);
	EPWM_Dead_Zone_Time_Config(EPWM12_SFR,EPWM_UP_EDGE_DEAD_ZONE,EPWM_DEAD_TIME);
	EPWM_Dead_Zone_Time_Config(EPWM12_SFR,EPWM_DOWM_EDGE_DEAD_ZONE,EPWM_DEAD_TIME);

	//TZ
	EPWM_Auto_ShowDown_Source_Select(EPWM12_SFR,EPWM_AUTO_SHOWDOWN_SOURCE_TZ4_HIGH);  //TZ4

	//interrupt
	//EPWM_INT_Enable(EPWM12_SFR,EPWM_COUNT_EQUAL_EPWMRA,FALSE);

	//update
	EPWM_Global_Loading_Enable(EPWM12_SFR,FALSE);
	EPWM_Updata_Event_Enable(EPWM12_SFR,TRUE);
	EPWM_Updata_Event_Generate_Enable(EPWM12_SFR,TRUE);


	EPWM_Enable(EPWM12_SFR,FALSE);
}

void cfg_EPWM13(void)
{
	EPWM_Work_Mode_Config(EPWM13_SFR,EPWM_TIMER_MODE);
	EPWM_Work_Clock_Select(EPWM13_SFR,EPWM_CLK_SCLK);  //EPWM_CLK=SCLK
	EPWM_TxPRSC_Value_Config(EPWM13_SFR,0);  //1:1
	EPWM_TxPHS_Value_Config(EPWM13_SFR,3);

	EPWM_Counter_Mode_Select(EPWM13_SFR,EPWM_COUNT_UP_DOWM_OF);  //UP DOWN MODE

	EPWM_Phase_Register_Loading_Enable(EPWM13_SFR,TRUE);
	EPWM_Phase_Direction_Config(EPWM13_SFR,EPWM_SYNC_TRIGGER_UP);
	EPWM_SYNC_Event_Out_Select(EPWM13_SFR,EPWM_SYNC_EVENT_OUT_EPWM_SWF);  //SYNCI/SWFSYNC

	EPWM13_SFR->PPX = EPWM_PERIOD;
	EPWM13_SFR->RA = EPWM_HALF_PERIOD;
	EPWM13_SFR->RB = EPWM_HALF_PERIOD;

	EPWM_EPWMxAB_OUTPUT_Select(EPWM13_SFR,EPWM_REGISTER_A,EPWM_CERA_DU_EPWMAB_OUT,EPWM_OUT_HIGH);    //RA-UP HIGH
	EPWM_EPWMxAB_OUTPUT_Select(EPWM13_SFR,EPWM_REGISTER_A,EPWM_CERA_DD_EPWMAB_OUT,EPWM_OUT_LOW);   //RA-DOWN LOW
	EPWM_Continuous_Mandatory_Output_Config(EPWM13_SFR,EPWM_REGISTER_A,EPWM_OUT_PROHIBIT);

	//DB
	EPWM_Dead_Zone_Input_Select(EPWM13_SFR,EPWM_EPWMA_UP_EPWMA_DOWM);
	EPWM_Dead_Zone_Output_Polarity_Select(EPWM13_SFR,EPWM_EPWMA_NTOGGLE_EPWMB_TOGGLE);
	EPWM_Dead_Zone_Output_Select(EPWM13_SFR,EPWM_UP_ENABLE_DOWN_ENABLE);
	EPWM_Dead_Zone_Time_Config(EPWM13_SFR,EPWM_UP_EDGE_DEAD_ZONE,EPWM_DEAD_TIME);
	EPWM_Dead_Zone_Time_Config(EPWM13_SFR,EPWM_DOWM_EDGE_DEAD_ZONE,EPWM_DEAD_TIME);

	//TZ
	EPWM_Auto_ShowDown_Source_Select(EPWM13_SFR,EPWM_AUTO_SHOWDOWN_SOURCE_TZ4_HIGH);  //TZ4

	//interrupt
	//EPWM_INT_Enable(EPWM13_SFR,EPWM_COUNT_EQUAL_EPWMRA,FALSE);

	//update
	EPWM_Global_Loading_Enable(EPWM13_SFR,FALSE);
	EPWM_Updata_Event_Enable(EPWM13_SFR,TRUE);
	EPWM_Updata_Event_Generate_Enable(EPWM13_SFR,TRUE);

	EPWM_Enable(EPWM13_SFR,FALSE);
}

void cfg_EPWM16(void)
{
	EPWM_Work_Mode_Config(EPWM16_SFR,EPWM_TIMER_MODE);
	EPWM_Work_Clock_Select(EPWM16_SFR,EPWM_CLK_SCLK);  //EPWM_CLK=SCLK
	EPWM_TxPRSC_Value_Config(EPWM16_SFR,0);  //1:1
	EPWM_TxPHS_Value_Config(EPWM16_SFR,4);

	EPWM_Counter_Mode_Select(EPWM16_SFR,EPWM_COUNT_UP_DOWM_OF);  //UP DOWN MODE

	EPWM_Phase_Register_Loading_Enable(EPWM16_SFR,TRUE);
	EPWM_Phase_Direction_Config(EPWM16_SFR,EPWM_SYNC_TRIGGER_UP);
	EPWM_SYNC_Event_Out_Select(EPWM16_SFR,EPWM_SYNC_EVENT_OUT_EPWM_SWF);  //SYNCI/SWFSYNC

	EPWM16_SFR->PPX = EPWM_PERIOD;
	EPWM16_SFR->RA = EPWM_HALF_PERIOD;
	EPWM16_SFR->RB = EPWM_HALF_PERIOD;

	EPWM_EPWMxAB_OUTPUT_Select(EPWM16_SFR,EPWM_REGISTER_A,EPWM_CE0_EPWMAB_OUT,EPWM_OUT_HIGH);    //CNT=0 HIGH
	EPWM_EPWMxAB_OUTPUT_Select(EPWM16_SFR,EPWM_REGISTER_A,EPWM_CEPPX_EPWMAB_OUT,EPWM_OUT_LOW);  //CNT=PPX  LOW

	EPWM_Continuous_Mandatory_Output_Config(EPWM16_SFR,EPWM_REGISTER_A,EPWM_OUT_PROHIBIT);

	//DB
/*	EPWM_Dead_Zone_Input_Select(EPWM16_SFR,EPWM_EPWMA_UP_EPWMA_DOWM);
	EPWM_Dead_Zone_Output_Polarity_Select(EPWM16_SFR,EPWM_EPWMA_NTOGGLE_EPWMB_TOGGLE);
	EPWM_Dead_Zone_Output_Select(EPWM16_SFR,EPWM_UP_ENABLE_DOWN_ENABLE);
	EPWM_Dead_Zone_Time_Config(EPWM16_SFR,EPWM_UP_EDGE_DEAD_ZONE,0);
	EPWM_Dead_Zone_Time_Config(EPWM16_SFR,EPWM_DOWM_EDGE_DEAD_ZONE,0);  */

	//TZ
	//EPWM_Auto_ShowDown_Source_Select(EPWM16_SFR,EPWM_AUTO_SHOWDOWN_SOURCE_TZ1_HIGH);  //TZ1

    //trigger AD
	EPWM_Trigger_AD_Event_Mode_Select(EPWM16_SFR,EPWM_TRIGGER_AD_EVENT0,EPWM_TRIGGER_AD_UP);
	EPWM_Trigger_AD_Event_Mode_Select(EPWM16_SFR,EPWM_TRIGGER_AD_EVENT1,EPWM_TRIGGER_AD_UP);
	EPWM_Trigger_Event_Cycle_Select(EPWM16_SFR,EPWM_TRIGGER_AD_EVENT0,EPWM_1_TRIGGER_EVENT_TRIGGER_AD);
	EPWM_Trigger_Event_Cycle_Select(EPWM16_SFR,EPWM_TRIGGER_AD_EVENT1,EPWM_1_TRIGGER_EVENT_TRIGGER_AD);
	EPWM_Trigger_AD_Event_Select(EPWM16_SFR,EPWM_TRIGGER_AD_EVENT0,EPWM_TIMER_EQUAL_DUTYA);
	EPWM_Trigger_AD_Event_Select(EPWM16_SFR,EPWM_TRIGGER_AD_EVENT1,EPWM_TIMER_EQUAL_DUTYB);
	EPWM_Trigger_AD_Event_Enable(EPWM16_SFR,EPWM_TRIGGER_AD_EVENT0,TRUE);
	EPWM_Trigger_AD_Event_Enable(EPWM16_SFR,EPWM_TRIGGER_AD_EVENT1,TRUE);

	//interrupt
	//EPWM_INT_Enable(EPWM16_SFR,EPWM_COUNT_EQUAL_EPWMRA,FALSE);

	//update
	EPWM_Global_Loading_Enable(EPWM16_SFR,FALSE);
	EPWM_Updata_Event_Enable(EPWM16_SFR,TRUE);
	EPWM_Updata_Event_Generate_Enable(EPWM16_SFR,TRUE);


	EPWM_Enable(EPWM16_SFR,TRUE);
}



void pwm_enable(void)
{
	EPWM11_SFR->RA = EPWM_HALF_PERIOD;
	EPWM12_SFR->RA = EPWM_HALF_PERIOD;
	EPWM13_SFR->RA = EPWM_HALF_PERIOD;
	EPWM11_SFR->PXASCTL = 0x0001;
	EPWM12_SFR->PXASCTL = 0x0001;
	EPWM13_SFR->PXASCTL = 0x0001;
}

void pwm_disable(void)
{
	EPWM11_SFR->PXASCTL = 0x0009;
	EPWM12_SFR->PXASCTL = 0x0009;
	EPWM13_SFR->PXASCTL = 0x0009;
}

void set_pwm_duty(uint16_t duty)
{
	volatile uint16_t compare_value;
	if(duty>100)
	{
		duty = 100;
	}
	compare_value = (uint32_t)(duty*EPWM_PERIOD)/100;
	EPWM11_SFR->RA = EPWM_PERIOD - compare_value;
	EPWM12_SFR->RA = EPWM_PERIOD - compare_value;
	EPWM13_SFR->RA = EPWM_PERIOD - compare_value;
}


void epwm_module_enable(void)
{
	EPWM_Enable(EPWM11_SFR,TRUE);
	EPWM_Enable(EPWM12_SFR,TRUE);
	EPWM_Enable(EPWM13_SFR,TRUE);
}






