

#include "system_init.h"


void cfg_FLEXMUX(void)
{
	FMUX_Reset();

//	FMUX_Work_CLK_Select(FMUX_CLK_HFCLK); /* 必须使用SCLK，否则可能导致丢失触发信号 */
	//TRIG4, CCP0CH2 trig ADC2 for PFC
/*	FMUX_Channel_Enable(FMUX_CHANNEL_4,TRUE);
	FMUX_Channel_Triggle_Source_Select(FMUX_CHANNEL_4,FMUX_CHANNEL_TRIGGLE_CCP0CH2);
	FMUX_Output_Select(FMUX_CHANNEL_4,FMUX_INPUT_OUTPUT); //FMUX_INPUT_SCK_SYNC_OUTPUT,FMUX_INPUT_OUTPUT */


	FMUX_Work_CLK_Select(FMUX_CLK_HFCLK);
	//TRIG1
	FMUX_Channel_Enable(FMUX_CHANNEL_1,TRUE);
	//FMUX_Channel_Triggle_Source_Select(FMUX_CHANNEL_1,FMUX_CHANNEL_TRIGGLE_CMP1_DIGITAL_OUTPUT);
	FMUX_Channel_Triggle_Source_Select(FMUX_CHANNEL_1,FMUX_CHANNEL_TRIGGLE_PF1PF8PA5);
	FMUX_Output_Select(FMUX_CHANNEL_1,FMUX_INPUT_SCK_SYNC_OUTPUT);
//	//TRIG2
//	FMUX_Channel_Enable(FMUX_CHANNEL_2,TRUE);
//	FMUX_Channel_Triggle_Source_Select(FMUX_CHANNEL_2,FMUX_CHANNEL_TRIGGLE_CMP1_DIGITAL_OUTPUT);
//	FMUX_Output_Select(FMUX_CHANNEL_2,FMUX_INPUT_SCK_SYNC_OUTPUT);
//	//TRIG3
//	FMUX_Channel_Enable(FMUX_CHANNEL_3,TRUE);
//	FMUX_Channel_Triggle_Source_Select(FMUX_CHANNEL_3,FMUX_CHANNEL_TRIGGLE_CMP1_DIGITAL_OUTPUT);
//	FMUX_Output_Select(FMUX_CHANNEL_3,FMUX_INPUT_SCK_SYNC_OUTPUT);



	FMUX_Enable(TRUE);

}
